# Databricks Apps Configuration
# See: https://docs.databricks.com/en/dev-tools/databricks-apps/index.html

command:
  - "uvicorn"
  - "backend.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  # Socrata API token for fetching public datasets
  - name: SOCRATA_APP_TOKEN
    description: "Socrata API token for accessing open data portals"
    # Set via Databricks Apps secrets or environment configuration

  # Azure OpenAI Configuration (optional - can also be set via UI)
  - name: AZURE_ENDPOINT
    description: "Azure OpenAI endpoint URL (e.g., https://your-resource.openai.azure.com/openai/v1/)"

  - name: AZURE_KEY
    description: "Azure OpenAI API key"

  - name: AZURE_MODEL
    description: "Azure OpenAI model deployment name (e.g., gpt-4)"
